services:
  postgres:
    image: postgres:15
    container_name: memoryleaf-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: jesuisadmin
      POSTGRES_DB: memoryleaf
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: memoryleaf-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: memoryleaf-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres
      - mongodb

volumes:
  pgdata:
  mongodata: