name: CI - MemoryLeaf (dev)

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  backend:
    name: Build and Test Backend (Dev)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      MONGODB_URL: ${{ secrets.MONGODB_URL }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        working-directory: ./backend
        run: npm install

      - name: Generate Prisma Client
        working-directory: ./backend
        run: npx prisma generate

      - name: Type check and build
        working-directory: ./backend
        run: npm run build

      - name: Run ESLint
        working-directory: ./backend
        run: npm run lint

      - name: Push Prisma schema to DB
        working-directory: ./backend
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Run tests
        working-directory: ./backend
        run: npm test || echo "No tests yet"
